### ISSUE TITLE
LCP 1.10 Upgrade – Outdated lcp-drm-patcher

### ISSUE THREAD

**Issue by BearVictor** [readium/readium-lcp-server#349]
We're upgrading LCP from version 1.7 to 1.10, but encountering issues with outdated DRM-related files.

Steps to Reproduce
1. Install LCP from source using the following steps:
```
git clone https://github.com/readium/readium-lcp-server.git
cd readium-lcp-server
git checkout V1.10.0


# These steps are taken from `lcp-drm-patcher` provided
# by Laurent Le Meur in July 2023.

#echo "Copying DRM specifics into build directory."
cp /root/installation/userkey.h license/
cp /root/installation/libuserkey.a license/
cp /root/installation/user_key.go license/

/usr/local/go/bin/go install ./...
```

2. Build fails with the following error:
```
# github.com/readium/readium-lcp-server/lcpserver  
lcpserver/lcpserver.go:72:50: undefined: license.LCP_PRODUCTION_LIB  

```

The above DRM-related files may be outdated or unnecessary in LCP 1.10.
The previous patch worked in version 1.7, but it is unclear if these files are still required.

**Questions**
1. Do we still need the drm-patcher in LCP 1.10?
2. Has the new LCP version incorporated this logic internally?

[Archive.zip](https://github.com/user-attachments/files/19106083/Archive.zip)

I've attached the mentioned files for you to look over. 
Thank you
